### PR TITLE
Add additional data types

### PR DESCRIPTION
**Pull request by OmarBizreh**
I know SQLite does not support Datetime and Bit (true or false) but
doing internal conversions will give developers more flexibility.

### CODE REVIEW

**Comment by remirobert** [comment]
Juste awesome !! I will add the Data type for store image and some date. Thanks again, thanks to you camembert will be a great librairy !!

**Comment by OmarBizreh** [comment]
You're welcome and thank you for giving me an Entity Framework like experience, where we can treat our database as classes. By the way my next move was adding file storage, since you are going to do it, I'll see what else I can include.

**Comment by remirobert** [comment]
perfect, it's great to work with you !!

**Comment by OmarBizreh** [comment]
Thank you and it is great to work with you too!!
By the way if I may suggest that you force contributers to follow one coding style. For example I am a .Net developer I am used to add a ; at the end of each line, so imagine adding ; for the code I write and not adding for the code you write, that will confuse people. If you have a style in mind I think it is better to include it in the Readme file so we can all follow one style.

**Pull request merged**
